var gvjs__ja={cEa:gvjs_Dx,SATELLITE:"satellite",TERRAIN:"terrain",HYBRID:gvjs_Fw},gvjs_0ja={mapType:gvjs_Fw,icons:{"default":{normal:"//maps.google.com/mapfiles/ms/micons/red-dot.png",selected:"//maps.google.com/mapfiles/ms/micons/blue-dot.png"}},enableScrollWheel:!1,showTip:!1,showLine:!1,lineColor:"#0033ff",lineWidth:10,useMapTypeControl:!1,zoomLevel:null};function gvjs_yW(a){gvjs_Tq.call(this,a);this.da=gvjs_dp(a);this.pd=new gvjs_Pq(this,this.da,!0);this.Cr=new gvjs_2p;this.S0=this.bK=this.dK=0;this.m=this.vc=this.XQ=this.xB=this.ir=this.xf=this.DF=this.FM=this.GQ=null;this.jga=this.so=!1}gvjs_p(gvjs_yW,gvjs_Tq);gvjs_=gvjs_yW.prototype;gvjs_.Qg=function(a,b,c){try{gvjs_ap(gvjs_o(this.boa,this,b,c))}catch(d){this.pd.ce(d.message||"error: cannot draw map")}};
gvjs_.boa=function(a,b){b=gvjs_Uh(gvjs_Rh(b||{}));this.m=new gvjs_oi([b,gvjs_0ja]);b=this.da;this.Cr.cancel();this.pd.removeAll();if(a){var c=0;gvjs_u.qa&&(c=7>gvjs_u.VERSION?50:6);b.offsetWidth<=c&&(b.style.width=gvjs_0o(b,this.m,400)+gvjs_H);b.offsetHeight<=c&&(b.style.height=gvjs_1o(b,this.m,400)+gvjs_H);try{var d=a.Z();if(0==d)throw Error(gvjs_$s);b=[];b.push(a.Y(0));if(b[0]==gvjs_f){if(3<d)throw Error("Only 1-3 columns allowed in address mode.");}else{if(2>d)throw Error("At least 2 columns are required in lat/long mode");
b.push(a.Y(1));if(b[0]!=gvjs_e)throw Error("First column must be numbers in lat/long mode.");if(b[1]!=gvjs_e)throw Error("Second column must be numbers in lat/long mode.");if(4<d)throw Error("Only 2-4 columns allowed in lat/long mode.");}}catch(g){this.pd.ce(gvjs_xt);return}this.sk();this.bK=d=a.ea();400<d&&(this.bK=400,gvjs_Sq(this.pd,"Some of the data rows were truncated"));b=a.Z();(d=a.Y(0)==gvjs_f)?(c=1<b?1:0,b=2<b?2:-1):(c=2<b?2:-1,b=3<b?3:-1);if(d){d=c;for(c=0;c<this.bK;c++)this.FM[c]={address:a.getStringValue(c,
0)||""},this.DF[c]=-1!=d?a.Ta(c,d):a.Ta(c,0),this.xf[c]=-1!==b?a.getStringValue(c,b)||gvjs_sv:gvjs_sv;null!=this.FM&&this.Cr.create(this.FM,gvjs_o(this.bra,this))}else{d=c;for(c=0;c<this.bK;c++){var e=a.getValue(c,0),f=a.getValue(c,1);null!=e&&null!=f&&90>e&&-90<e&&180>f&&-180<f?(this.DF[c]=-1!=d?a.Ta(c,d):e+" "+f,this.xf[c]=-1!==b?a.getStringValue(c,b)||gvjs_sv:gvjs_sv,e=new google.maps.LatLng(e,f,!0),this.GQ.push({point:e,title:this.DF[c]}),this.XQ.push(c),this.xB.push(this.S0++)):this.xB.push(-1)}gvjs_zW(this)}}else this.pd.ce(gvjs_bt)};
function gvjs_AW(a,b){switch(a){case gvjs_Fw:return google.maps.MapTypeId.HYBRID;case gvjs_Dx:return google.maps.MapTypeId.ROADMAP;case "satellite":return google.maps.MapTypeId.SATELLITE;case "terrain":return google.maps.MapTypeId.TERRAIN}return b}
gvjs_.sk=function(){var a=this.m;this.vc=new gvjs_br;var b=gvjs_D(a,"showTip");this.so=gvjs_D(a,"showInfoWindow",b);this.jga=gvjs_D(a,gvjs_Jy,b);this.GQ=[];this.FM=[];this.DF=[];this.xf=[];this.ir=[];this.xB=[];this.XQ=[];this.S0=this.bK=this.dK=0;b={mapTypeControl:gvjs_D(a,gvjs_vz),mapTypeControlOptions:{},navigationControl:!0,scrollwheel:gvjs_D(a,gvjs_Dv),navigationControlOptions:{style:gvjs_D(a,gvjs_uz)?google.maps.ZoomControlStyle.DEFAULT:google.maps.ZoomControlStyle.SMALL}};var c={},d={},e=gvjs_cba(a);
if(0<e.length){gvjs_q(e,function(b){d[b]=a.view(gvjs_qi("maps",b))});var f=0;gvjs_s(d,function(a,b){var d=a.Sb(gvjs_Ax);null!=d&&(f++,c[b]=new google.maps.StyledMapType(gvjs_Ai(a,"styles"),{name:d}))});e=a.cD("mapTypeIds");null!=e?e=gvjs_r(e,function(a){return gvjs_AW(a,a)},this):0<f&&(e=gvjs_Uc([google.maps.MapTypeId.ROADMAP,google.maps.MapTypeId.TERRAIN,google.maps.MapTypeId.SATELLITE,google.maps.MapTypeId.HYBRID],gvjs_re(c)));b.mapTypeControlOptions.mapTypeIds=e}this.jb=new google.maps.Map(this.da,
b);gvjs_s(c,function(a,b){this.jb.mapTypes.set(b,a)},this);this.cJ=new google.maps.InfoWindow;b=this.jb;e=google.maps.MapTypeId.HYBRID;var g=a.Sb(gvjs_$w);null!=g&&g in c?e=g:(g=gvjs_C(a,gvjs_$w,void 0,gvjs__ja),e=gvjs_AW(g,e));b.setMapTypeId(e)};gvjs_.bra=function(a){for(var b=0;b<a.length;b++)a[b]&&a[b][0]?(this.GQ.push({point:a[b][0].geometry.location,title:this.so?this.DF[this.dK]:null}),this.XQ.push(this.dK),this.xB.push(this.S0++)):this.xB.push(-1),this.dK+=1;gvjs_zW(this)};
function gvjs_zW(a){var b=a.GQ;if(0==b.length)gvjs_Sq(a.pd,"No data points to show on map");else{for(var c=a.jb,d=new google.maps.LatLngBounds,e,f,g=[],h=0;h<b.length;h++)if(e=b[h],f=e.point)g.push(f),d.extend(f);f=a.m;h=f.Ga("zoomLevel");null!=h?(c.setZoom(h),c.setCenter(d.getCenter())):c.fitBounds(d);for(h=0;h<b.length;h++)d=a.xf[h],e=b[h],e.point&&(d={map:c,position:e.point,icon:gvjs_C(f,"icons."+d+".normal")},a.jga&&(d.title=e.title),a.ir[h]=new google.maps.Marker(d),google.maps.event.addListener(a.ir[h],
gvjs_Uj,gvjs_o(a.wra,a,a.ir[h],a.XQ[h])));gvjs_D(f,gvjs_Iy)&&(b=gvjs_C(f,"lineColor"),f=gvjs_E(f,"lineWeight"),(new google.maps.Polyline({path:g,strokeColor:b,strokeWeight:f})).setMap(c));google.maps.event.addListener(c,"tilesloaded",gvjs_o(gvjs_T,a,a,gvjs_I,null))}}
gvjs_.wra=function(a,b){var c=gvjs_fr(this.vc,b)?null:[{row:b}];this.setSelection(c);gvjs_T(this,gvjs_J,{});c&&this.so?(this.cJ.close(),b=this.DF[b],gvjs_D(this.m,gvjs_Ut,!0)?this.cJ.setContent(b):this.cJ.setContent(document.createTextNode(String(b))),this.cJ.open(this.jb,a)):this.cJ.close()};
gvjs_.setSelection=function(a){var b=this.vc.setSelection(a);a=this.xB;for(var c=this.ir,d=this.xf,e,f,g=this.jb,h=gvjs_dr(b.zE),k=0;k<h.length;k++)f=h[k],e=c[a[f]],f=d[a[f]],e&&e.setIcon(gvjs_C(this.m,"icons."+f+".normal"));b=gvjs_dr(b.wB);for(k=0;k<b.length;k++)f=b[k],e=c[a[f]],f=d[a[f]],e&&e.setIcon(gvjs_C(this.m,"icons."+f+".selected"));e&&g.panTo(e.getPosition())};gvjs_.getSelection=function(){return this.vc.getSelection()};gvjs_.Wb=function(){this.Cr.cancel()};gvjs_k(gvjs_Vk,gvjs_yW,void 0);gvjs_yW.prototype.draw=gvjs_yW.prototype.draw;gvjs_yW.prototype.setSelection=gvjs_yW.prototype.setSelection;gvjs_yW.prototype.getSelection=gvjs_yW.prototype.getSelection;
